### PR TITLE
Webserver config

### PR DESCRIPTION
**Pull request by roperto**
The CI is going to fail because of master, but you can review the documentation part and I will fix CI after the #53 is merged.

### CODE REVIEW

**Comment by brendanheywood** [comment]
@roperto has this been tested under nginx when moodle is installed into a subdirectory like http://moodle.com/moodle/  ?

**Comment by brendanheywood** [comment]
Also now that this is much more succinct (awesome!) is there any point to having the two .md files, why not just merge that into the main readme as a new sub section?

**Comment by roperto** [comment]
Hi @brendanheywood 

1) No I have not tested with moodle in a subdir and I think it is worth testing, thanks for the reminder.

2) I think this is short enough to just be merged into the README now.

3) After changing to README.md I need to change the instructions link in the settings page to point to README instead.

I will address that tomorrow and ask you to review again.

Cheers,

Daniel

**Comment by roperto** [comment]
Hi @brendanheywood , I addressed the points discussed before.

Can you review it again?

Thanks

Daniel

**Pull request merged**
